@bruninToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRhMDRlNTNiLTdjNWUtNGM0My1iN2EzLTE0MjhjZjZlZjc5MSIsInJvbGVzIjpbeyJpZCI6IjIxZTZkMjYyLWU4YjgtNGExYS1iNDc3LWU0YTA4ZmJmMzdhNyJ9LHsiaWQiOiJjYmFmNmRjMS03MzBiLTQ5ZjctODExNS04OTZmYTY4MGNkOGEifV19.ZID1utrLbgkjScTuIRxmNJzpYQ463uNkWEger8UoZNs

@baseUrl = http://localhost:3333

###
POST {{baseUrl}}/locations/types
Content-Type: application/json
Authorization: Bearer {{bruninToken}}

{
  "name": "Sala"
}