@bruninToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRhMDRlNTNiLTdjNWUtNGM0My1iN2EzLTE0MjhjZjZlZjc5MSIsInJvbGVzIjpbeyJpZCI6IjIxZTZkMjYyLWU4YjgtNGExYS1iNDc3LWU0YTA4ZmJmMzdhNyJ9LHsiaWQiOiJjYmFmNmRjMS03MzBiLTQ5ZjctODExNS04OTZmYTY4MGNkOGEifV19.ZID1utrLbgkjScTuIRxmNJzpYQ463uNkWEger8UoZNs
@bruninId = da04e53b-7c5e-4c43-b7a3-1428cf6ef791
@madonoId = f1f229aa-f477-436d-a63b-38dd3d521e3a

@testeId = ec6bb113-5291-48ec-9045-e4a8e4f7881f

@baseUrl = http://localhost:3333

POST {{baseUrl}}/teachers
Content-Type: application/json
Authorization: Bearer {{bruninToken}}

{   
    "name": 1
}

###
PATCH {{baseUrl}}/teachers/2f8ec483-611e-499b-9f9b-8ff54d48eab4
Content-Type: application/json
Authorization: Bearer {{bruninToken}}

{   
    "telephone": "6996969696"
}