@baseUrl = http://localhost:3333

@bruninId = da04e53b-7c5e-4c43-b7a3-1428cf6ef791
@madonoId = f1f229aa-f477-436d-a63b-38dd3d521e3a

# Dave
@roleId = cbaf6dc1-730b-49f7-8115-896fa680cd8a



###
POST {{baseUrl}}/users/{{bruninId}}/roles
Content-Type: application/json

{
    "roleId": "{{roleId}}"
}

###
POST {{baseUrl}}/users/{{madonoId}}/roles
Content-Type: application/json 

{
    "roleId": "{{roleId}}"
}