@bruninToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRhMDRlNTNiLTdjNWUtNGM0My1iN2EzLTE0MjhjZjZlZjc5MSIsInJvbGVzIjpbeyJpZCI6IjIxZTZkMjYyLWU4YjgtNGExYS1iNDc3LWU0YTA4ZmJmMzdhNyJ9LHsiaWQiOiJjYmFmNmRjMS03MzBiLTQ5ZjctODExNS04OTZmYTY4MGNkOGEifV19.ZID1utrLbgkjScTuIRxmNJzpYQ463uNkWEger8UoZNs
@bruninId = da04e53b-7c5e-4c43-b7a3-1428cf6ef791
@madonoId = f1f229aa-f477-436d-a63b-38dd3d521e3a

@testeId = ec6bb113-5291-48ec-9045-e4a8e4f7881f

### =========================
### GET /users
### Lista usuários
### =========================
GET http://localhost:3333/users
Content-Type: application/json
Authorization: Bearer {{bruninToken}}



### =========================
### GET /users/:id
### Usuário existente
### =========================
GET http://localhost:3333/users/{{bruninId}}
Content-Type: application/json
Authorization: Bearer {{bruninToken}}
###
GET http://localhost:3333/users/{{madonoId}}
Content-Type: application/json
Authorization: Bearer {{bruninToken}}



### =========================
### GET /users/:id
### ID inválido
### =========================
GET http://localhost:3333/users/123
Content-Type: application/json
Authorization: Bearer {{bruninToken}}



### =========================
### POST /users
### Criar usuário
### =========================
POST http://localhost:3333/users
Content-Type: application/json
Authorization: Bearer {{bruninToken}}

{
  "name": "Alissong",
  "email": "alisson@gmail.com",
  "password": "iwehriowberwoirhwbeorih"
}



### =========================
### POST /users
### Email duplicado
### =========================
POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "Clone do Bruno",
  "email": "brunin9298@gmail.com",
  "password": "outra-senha"
}

### =========================
### PATCH /users/:id
### Atualiza só email
### =========================
PATCH http://localhost:3333/users/{{bruninId}}
Content-Type: application/json
Authorization: Bearer {{bruninToken}}

{
  "name": "TESTE"
}



### =========================
### PATCH /users/:id
### Atualiza email + senha
### =========================
PATCH http://localhost:3333/users/cf363c0c-34b0-41fb-afa8-4da990397402
Content-Type: application/json

{
  "email": "email.patch2@gmail.com",
  "password": "senha-patch"
}



### =========================
### PATCH /users/:id
### Body vazio (espera erro)
### =========================
PATCH http://localhost:3333/users/cf363c0c-34b0-41fb-afa8-4da990397402
Content-Type: application/json

{}



### =========================
### DELETE /users/:id
### Remove usuário
### =========================
DELETE http://localhost:3333/users/cf363c0c-34b0-41fb-afa8-4da990397402



### =========================
### DELETE /users/:id
### Usuário inexistente
### =========================
DELETE http://localhost:3333/users/00000000-0000-0000-0000-000000000000



